// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {todo} from '../models';

export function BulkDeleteDoneTodos():Promise<number>;

export function CloseToTray():Promise<void>;

export function CompleteTodo(arg1:number):Promise<void>;

export function CreateCategory(arg1:main.CreateCategoryRequest):Promise<number>;

export function CreateRecurringTask(arg1:main.CreateRecurringTaskRequest):Promise<number>;

export function CreateTodo(arg1:main.CreateTodoRequest):Promise<number>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteRecurringTask(arg1:number):Promise<void>;

export function DeleteTodo(arg1:number):Promise<void>;

export function GetCategories():Promise<Array<todo.Category>>;

export function GetNearOrOverdueMemos():Promise<Array<todo.Todo>>;

export function GetRecurringPanel():Promise<todo.RecurringPanelData>;

export function GetRecurringTask(arg1:number):Promise<todo.RecurringTask>;

export function GetRecurringTasks():Promise<Array<todo.RecurringTask>>;

export function GetSettings():Promise<todo.Settings>;

export function GetTodo(arg1:number):Promise<todo.Todo>;

export function GetTodos(arg1:string):Promise<Array<todo.Todo>>;

export function OpenImage(arg1:string):Promise<void>;

export function OpenLocalPath(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function ReorderCategories(arg1:Array<number>):Promise<void>;

export function ReorderTodos(arg1:Array<number>):Promise<void>;

export function RestoreTodo(arg1:number):Promise<void>;

export function SaveImage(arg1:string):Promise<string>;

export function SaveSettings(arg1:main.SaveSettingsRequest):Promise<todo.Settings>;

export function SnoozeReminder(arg1:number,arg2:string):Promise<void>;

export function ToggleImportant(arg1:number):Promise<void>;

export function ToggleRecurringTask(arg1:number):Promise<void>;

export function UpdateCategory(arg1:number,arg2:main.UpdateCategoryRequest):Promise<void>;

export function UpdateRecurringTask(arg1:number,arg2:main.UpdateRecurringTaskRequest):Promise<void>;

export function UpdateTodo(arg1:number,arg2:main.UpdateTodoRequest):Promise<void>;
